---
# This is to create an instance 
- name: Provide EC2 Instances
  hosts: localhost # Where the code will be executed 
  gather_facts: false # Useful for gathering information but not needed
  vars: 
    region: us-east-1
    instance_type: t2.micro 
    security_group: default
    ami_id: ami_1234 # Random placeholder ami_id
    aws: simplephplogin 
    count: 1

  tasks:
    - name: Create EC2 instance
      ec2_instance :  
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ secuirty_group }}"
        image: "{{ ami_id }}"
        keypair: simplephplogin
        count: "{{ count }}"
      register: ec2_instances

    - name : Display EC2 Instances Information
      debug: 
        var: ec2_instances.instances
